In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
from lane_detection import *
from lane_following import *

In [2]:
cap = cv2.VideoCapture('AUV_Vid.mkv')
ret, frame = cap.read()

In [3]:
lines = lane_detection.detect_lines(frame)
print(lines)

None


In [4]:
lane_detection.draw_lines(frame, lines)

array([[[ 88, 100,  79],
        [ 88, 100,  79],
        [ 89, 101,  80],
        ...,
        [ 74,  79,  59],
        [ 74,  79,  59],
        [ 74,  79,  59]],

       [[ 89, 101,  80],
        [ 89, 101,  80],
        [ 89, 101,  80],
        ...,
        [ 74,  79,  59],
        [ 74,  79,  59],
        [ 74,  79,  59]],

       [[ 91, 102,  83],
        [ 91, 102,  83],
        [ 91, 102,  83],
        ...,
        [ 76,  79,  59],
        [ 76,  79,  59],
        [ 76,  79,  59]],

       ...,

       [[ 88, 102,  89],
        [ 88, 102,  89],
        [ 88, 102,  89],
        ...,
        [ 87,  95,  91],
        [ 87,  95,  91],
        [ 87,  95,  91]],

       [[ 93, 100,  93],
        [ 93, 100,  93],
        [ 93, 100,  93],
        ...,
        [ 89,  95,  91],
        [ 89,  95,  91],
        [ 89,  95,  91]],

       [[ 93, 100,  93],
        [ 93, 100,  93],
        [ 93, 100,  93],
        ...,
        [ 90,  96,  93],
        [ 90,  96,  93],
        [ 90,  96,  93]]

In [5]:
slopeList, interceptList = lane_detection.get_slopes_intercepts(lines)



TypeError: 'NoneType' object is not iterable

In [ ]:
lane_detection.detect_lanes(lines)
lanes = lane_detection.detect_lanes(lines)

[[[592 385 797 741]]

 [[525 358 608 631]]

 [[670 522 797 742]]

 [[560 328 653 490]]

 [[560 475 641 742]]]
[1.7365853658536585]
[1.7365853658536585, 3.289156626506024]
[1.7365853658536585, 3.289156626506024, 1.7322834645669292]
[1.7365853658536585, 3.289156626506024, 1.7322834645669292, 1.7419354838709677]
[1.7365853658536585, 3.289156626506024, 1.7322834645669292, 1.7419354838709677, 3.2962962962962963]
5 5
[]
[[[592 385 797 741]]

 [[525 358 608 631]]

 [[670 522 797 742]]

 [[560 328 653 490]]

 [[560 475 641 742]]]
[1.7365853658536585]
[1.7365853658536585, 3.289156626506024]
[1.7365853658536585, 3.289156626506024, 1.7322834645669292]
[1.7365853658536585, 3.289156626506024, 1.7322834645669292, 1.7419354838709677]
[1.7365853658536585, 3.289156626506024, 1.7322834645669292, 1.7419354838709677, 3.2962962962962963]
5 5
[]


In [ ]:
cv2.line(frame, 429, 1080, 573, 299)
plt.imshow(frame, cv2.COLOR_BGR2RGB)
plt.show()

error: OpenCV(4.8.0) :-1: error: (-5:Bad argument) in function 'line'
> Overload resolution failed:
>  - Can't parse 'pt1'. Input argument doesn't provide sequence protocol
>  - Can't parse 'pt1'. Input argument doesn't provide sequence protocol
