In [17]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
from lane_detection import *
from lane_following import *

In [18]:
img = cv2.imread("rov_pool.jpg")

In [19]:
lines = lane_detection.detect_lines(img)
print(lines)

[[[592 385 797 741]]

 [[525 358 608 631]]

 [[670 522 797 742]]

 [[560 328 653 490]]

 [[560 475 641 742]]]


In [20]:
lane_detection.draw_lines(img, lines)

[592 385 797 741]
[525 358 608 631]
[670 522 797 742]
[560 328 653 490]
[560 475 641 742]


array([[[107,  86,  48],
        [107,  86,  48],
        [107,  86,  48],
        ...,
        [ 86,  55,  32],
        [ 86,  55,  32],
        [ 86,  55,  32]],

       [[107,  86,  48],
        [107,  86,  48],
        [107,  86,  48],
        ...,
        [ 86,  55,  32],
        [ 86,  55,  32],
        [ 86,  55,  32]],

       [[107,  86,  48],
        [107,  86,  48],
        [107,  86,  48],
        ...,
        [ 86,  55,  32],
        [ 86,  55,  32],
        [ 86,  55,  32]],

       ...,

       [[100, 105, 104],
        [101, 106, 105],
        [101, 106, 105],
        ...,
        [104, 103, 105],
        [104, 104, 104],
        [104, 104, 104]],

       [[100, 105, 104],
        [100, 105, 104],
        [101, 106, 105],
        ...,
        [104, 103, 105],
        [104, 104, 104],
        [104, 104, 104]],

       [[100, 105, 104],
        [100, 105, 104],
        [100, 105, 104],
        ...,
        [104, 103, 105],
        [104, 104, 104],
        [104, 104, 104]]

In [21]:
slopeList, interceptList = lane_detection.get_slopes_intercepts(lines)



[1.7365853658536585]
[1.7365853658536585, 3.289156626506024]
[1.7365853658536585, 3.289156626506024, 1.7322834645669292]
[1.7365853658536585, 3.289156626506024, 1.7322834645669292, 1.7419354838709677]
[1.7365853658536585, 3.289156626506024, 1.7322834645669292, 1.7419354838709677, 3.2962962962962963]


In [22]:
lane_detection.detect_lanes(lines)
lanes = lane_detection.detect_lanes(lines)

[[[592 385 797 741]]

 [[525 358 608 631]]

 [[670 522 797 742]]

 [[560 328 653 490]]

 [[560 475 641 742]]]
[1.7365853658536585]
[1.7365853658536585, 3.289156626506024]
[1.7365853658536585, 3.289156626506024, 1.7322834645669292]
[1.7365853658536585, 3.289156626506024, 1.7322834645669292, 1.7419354838709677]
[1.7365853658536585, 3.289156626506024, 1.7322834645669292, 1.7419354838709677, 3.2962962962962963]
5 5
[]
[[[592 385 797 741]]

 [[525 358 608 631]]

 [[670 522 797 742]]

 [[560 328 653 490]]

 [[560 475 641 742]]]
[1.7365853658536585]
[1.7365853658536585, 3.289156626506024]
[1.7365853658536585, 3.289156626506024, 1.7322834645669292]
[1.7365853658536585, 3.289156626506024, 1.7322834645669292, 1.7419354838709677]
[1.7365853658536585, 3.289156626506024, 1.7322834645669292, 1.7419354838709677, 3.2962962962962963]
5 5
[]


In [23]:
img = cv2.imread("rov_pool.jpg")

In [24]:
cv2.line(img, 429, 1080, 573, 299)
plt.imshow(img, cv2.COLOR_BGR2RGB)
plt.show()

error: OpenCV(4.8.0) :-1: error: (-5:Bad argument) in function 'line'
> Overload resolution failed:
>  - Can't parse 'pt1'. Input argument doesn't provide sequence protocol
>  - Can't parse 'pt1'. Input argument doesn't provide sequence protocol
